"""Active, utility-blind extraction semantics for MP and ME atoms.

MS is intentionally absent: it is the complete raw session transcript and is
compiled mechanically, not generated by a semantic extractor.
"""

from metacom_pm.io import sha256_text


MULTI_VIEW_EXTRACTOR_SYSTEM_PROMPT = """You extract factual Multi-View Memory atoms from user-authored dialogue spans.

MP is the target-time Current Profile View. Extract only stable, slot-like facts
such as identity, occupation, education, location, stable relationship roles,
durable health constraints, enduring interests/preferences, and durable
boundaries. Do not put temporary emotions, short-term stress, one-off
situations, or time-varying episodes into MP. Give each MP fact a stable
profile_slot_key so later disclosed values can update the current view.

ME is the strict-past Atomic Event/Experience Timeline. Extract occurred life
or relationship events, state onset/change, temporary states, meaningful
experiences, coping attempts, support experiences, and other occurred events.
Action followed by a user-observed outcome is one ME subtype, not the definition
of ME. Do not require every ME item to have action/outcome fields.

User-anchored facts about another person are allowed when the user's own life,
relationship, experience, or support context is affected. Preserve exact user
source spans. Do not use dataset summaries, observations, profile metadata,
gold answers, evaluator fields, future sessions, supporter-only claims, or
general knowledge. Never judge relevance, usefulness, response quality,
ON/OFF effect, or whether a resource should be opened. Empty arrays are valid.

Do not emit MS atoms. MS is constructed separately as one complete raw
strictly-past session transcript."""

MULTI_VIEW_VERIFIER_SYSTEM_PROMPT = """Verify only factual grounding and ontology membership of proposed MP/ME atoms.

Accept MP only for a stable current-profile slot grounded in exact user text;
reject transient emotion, short-term stress, and one-off episodes as MP. Accept
ME for occurred or ongoing-stage event/experience timeline atoms. Require
action_text and observed_outcome_text only for the action_observed_outcome ME
subtype. User-anchored third-party events are allowed. Reject invented facts,
wrong owner, future/hypothetical content, supporter-only claims, and span
mismatch. Never judge utility, treatment choice, response quality, or effect.
Do not create, rewrite, or relabel a proposal."""

MULTI_VIEW_EXTRACTOR_USER_INSTRUCTION = (
    "Return one JSON object matching the schema. Proposal IDs and span IDs must be "
    "unique within this session. Use the compact schema keys exactly. Every s item "
    "must contain only i, set to a supplied seeker turn_id; the runtime restores the "
    "complete exact turn as evidence. In prior_current_profile, t is profile_field_type, "
    "k is profile_slot_key, and v is normalized_value. It is context only for reusing "
    "stable profile_slot_key values; "
    "do not repeat a prior fact unless the current session reaffirms or updates it."
)
MULTI_VIEW_VERIFIER_USER_INSTRUCTION = (
    "Return one compact JSON object with exactly one d decision for every supplied "
    "proposal_id and no other IDs. Set i to proposal_id and r to one schema reason. "
    "Do not repair a proposal."
)

MULTI_VIEW_EXTRACTOR_PROMPT_SHA256 = sha256_text(MULTI_VIEW_EXTRACTOR_SYSTEM_PROMPT)
MULTI_VIEW_VERIFIER_PROMPT_SHA256 = sha256_text(MULTI_VIEW_VERIFIER_SYSTEM_PROMPT)
MULTI_VIEW_EXTRACTOR_MESSAGE_TEMPLATE_SHA256 = sha256_text(
    MULTI_VIEW_EXTRACTOR_USER_INSTRUCTION + "\n\nINPUT:\n{source}\n\nSCHEMA:\n{schema}"
)
MULTI_VIEW_VERIFIER_MESSAGE_TEMPLATE_SHA256 = sha256_text(
    MULTI_VIEW_VERIFIER_USER_INSTRUCTION
    + "\n\nINPUT:\n{source}\n\nPROPOSALS:\n{proposals}\n\nSCHEMA:\n{schema}"
)


def extractor_messages(source_json: str, strict_schema_json: str) -> list[dict[str, str]]:
    return [
        {"role": "system", "content": MULTI_VIEW_EXTRACTOR_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                MULTI_VIEW_EXTRACTOR_USER_INSTRUCTION
                + "\n\nINPUT:\n"
                + source_json
                + "\n\nSCHEMA:\n"
                + strict_schema_json
            ),
        },
    ]


def verifier_messages(
    source_json: str,
    proposals_json: str,
    strict_schema_json: str,
) -> list[dict[str, str]]:
    return [
        {"role": "system", "content": MULTI_VIEW_VERIFIER_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                MULTI_VIEW_VERIFIER_USER_INSTRUCTION
                + "\n\nINPUT:\n"
                + source_json
                + "\n\nPROPOSALS:\n"
                + proposals_json
                + "\n\nSCHEMA:\n"
                + strict_schema_json
            ),
        },
    ]


__all__ = [
    "MULTI_VIEW_EXTRACTOR_PROMPT_SHA256",
    "MULTI_VIEW_EXTRACTOR_MESSAGE_TEMPLATE_SHA256",
    "MULTI_VIEW_EXTRACTOR_SYSTEM_PROMPT",
    "MULTI_VIEW_VERIFIER_PROMPT_SHA256",
    "MULTI_VIEW_VERIFIER_MESSAGE_TEMPLATE_SHA256",
    "MULTI_VIEW_VERIFIER_SYSTEM_PROMPT",
    "extractor_messages",
    "verifier_messages",
]
