"""Active, utility-blind extraction semantics for MP and ME atoms.

MS is intentionally absent: it is the complete raw session transcript and is
compiled mechanically, not generated by a semantic extractor.
"""

from metacom_pm.io import sha256_text


MULTI_VIEW_EXTRACTOR_SYSTEM_PROMPT = """You extract factual Multi-View Memory atoms from user-authored dialogue spans.

MP is the target-time Current Profile View. Extract only stable, slot-like facts
such as identity, occupation, education, location, stable relationship roles,
durable health constraints, enduring interests/preferences, and durable
boundaries. Do not put temporary emotions, short-term stress, one-off
situations, or time-varying episodes into MP. Give each MP fact a stable
profile_slot_key so later disclosed values can update the current view.

ME is the strict-past Atomic Event/Experience Timeline. Extract occurred life
or relationship events, state onset/change, temporary states, meaningful
experiences, coping attempts, support experiences, and other occurred events.
Action followed by a user-observed outcome is one ME subtype, not the definition
of ME. Do not require every ME item to have action/outcome fields.

User-anchored facts about another person are allowed when the user's own life,
relationship, experience, or support context is affected. Preserve exact user
source spans. Do not use dataset summaries, observations, profile metadata,
gold answers, evaluator fields, future sessions, supporter-only claims, or
general knowledge. Never judge relevance, usefulness, response quality,
ON/OFF effect, or whether a resource should be opened. Empty arrays are valid.

Do not emit MS atoms. MS is constructed separately as one complete raw
strictly-past session transcript."""

MULTI_VIEW_VERIFIER_SYSTEM_PROMPT = """Verify only factual grounding and ontology membership of proposed MP/ME atoms.

Accept MP only for a stable current-profile slot grounded in exact user text;
reject transient emotion, short-term stress, and one-off episodes as MP. Accept
ME for occurred or ongoing-stage event/experience timeline atoms. Require
action_text and observed_outcome_text only for the action_observed_outcome ME
subtype. User-anchored third-party events are allowed. Reject invented facts,
wrong owner, future/hypothetical content, supporter-only claims, and span
mismatch. Never judge utility, treatment choice, response quality, or effect.
Do not create, rewrite, or relabel a proposal."""

MULTI_VIEW_EXTRACTOR_PROMPT_SHA256 = sha256_text(MULTI_VIEW_EXTRACTOR_SYSTEM_PROMPT)
MULTI_VIEW_VERIFIER_PROMPT_SHA256 = sha256_text(MULTI_VIEW_VERIFIER_SYSTEM_PROMPT)


__all__ = [
    "MULTI_VIEW_EXTRACTOR_PROMPT_SHA256",
    "MULTI_VIEW_EXTRACTOR_SYSTEM_PROMPT",
    "MULTI_VIEW_VERIFIER_PROMPT_SHA256",
    "MULTI_VIEW_VERIFIER_SYSTEM_PROMPT",
]
