#!/usr/bin/env python3
"""Materialize (zero-API) the blind-review judge manifest for the RS/MS
Panel V2, reusing the 50 real replies already generated by 329l -- no new
generation. Per paper1_panel_v2_owner_cluster_correction_and_roadmap_v1.json
#six_step_roadmap.step_2_blind_review_manifest:

  RS: M0+R0 vs M0+RS Quality (pairwise) + strategy realization (Function-
      style, blind to arm, shown the authorized RS card); absolute Risk on
      both arms.
  MS: M0+R0 vs MS+R0 Quality (pairwise) + Risk (absolute, both arms);
      independent blind Function re-verification of the 5 CLEAR_USE + 2 ASK
      states (redoing 330l's first-party read, blind this time).
  Interaction: the same Function instrument applied to MS+RS on the same 7
      states, to check whether RS crowds out MS's observable contribution.

Every call is tagged with an owner_cluster key so later analysis can
collapse evo::p1's two panel states (CLEAR_USE + IGNORE_low_information_
greeting) into one cluster instead of counting them as independent.

Uses the exact same instrument module as every prior quality/risk track
this session (v1_5_rs_ms_quality_risk_blind_review.py, unmodified) plus the
new Function Observability V2 blind reviewer for the taxonomy this session
adopted. No generator or judge call is made here.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from metacom_pm.io import canonical_json, read_json, read_jsonl, sha256_text, write_json, write_jsonl  # noqa: E402
from metacom_pm.v1_5_function_observability_v2_blind_review import (  # noqa: E402
    FunctionObservabilityV2BlindReview,
    function_prompt_messages,
)
from metacom_pm.v1_5_rs_ms_quality_risk_blind_review import (  # noqa: E402
    RSMSQualityBlindReview,
    RSMSRiskBlindReview,
    quality_prompt_messages,
    risk_prompt_messages,
)

CASES = ROOT / "outputs/pm_v1_5_paper1_rs_ms_panel_v2_20260813/development_cases_private.jsonl"
STATES = ROOT / "outputs/pm_v1_5_paper1_p1_public_surface/evoemo_states_unlabeled.jsonl"
RESULTS = ROOT / "outputs/pm_v1_5_paper1_rs_ms_panel_v2_live_20260813/generator_results_private.jsonl"
QUALIFIED_CARDS = ROOT / "outputs/pm_v1_5_paper1_rs_strategy_card_llm_audit_qualified_bank_20260812/strategy_cards_v4_llm_audit_qualified_only.jsonl"
RELEASE_MANIFEST = ROOT / "outputs/pm_v1_5_paid_run_release.json"
OUT = ROOT / "outputs/pm_v1_5_paper1_rs_ms_panel_v2_blind_review_manifest_20260813"
STAGE = "paper1_rs_ms_panel_v2_blind_review_v1"
REVIEWER_ID = "RS_MS_PANEL_V2_BLIND_REVIEW_GPT56"
ENDPOINT_KEY = "openai_gpt_5_6_sol"
FUNCTION_STATES = {"CLEAR_USE", "ASK"}
# Historical blended rate: 57 calls (19 quality + 38 risk) cost $0.5756 =>
# ~$0.0101/call. Function-style calls carry more context (current + source +
# reply vs quality's current + 2 replies or risk's current + 1 reply), so a
# higher per-call estimate is used for those specifically.
QUALITY_RISK_USD_PER_CALL = 0.0101
FUNCTION_USD_PER_CALL = 0.016


def _compact(value: object) -> str:
    return " ".join(str(value or "").split())


def stable_hex(*values: object, length: int = 24) -> str:
    text = "\x1f".join(str(value) for value in values)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:length]


def main() -> None:
    if OUT.exists():
        raise RuntimeError("blind review manifest already materialized; refusing overwrite")

    cases = {row["case_id"]: row for row in read_jsonl(CASES)}
    states = {row["state_id"]: row for row in read_jsonl(STATES)}
    results = {(row["case_id"], row["arm"]): row for row in read_jsonl(RESULTS)}
    cards = {row["card_id"]: row for row in read_jsonl(QUALIFIED_CARDS)}
    if len(results) != 50:
        raise RuntimeError(f"expected 50 real replies, found {len(results)}")

    quality_calls: list[dict[str, Any]] = []
    risk_calls: list[dict[str, Any]] = []
    function_calls: list[dict[str, Any]] = []
    risk_call_by_key: dict[tuple[str, str], dict[str, Any]] = {}
    private_map: list[dict[str, Any]] = []

    def get_risk_call(case_id: str, arm: str, owner: str, dialogue: str) -> str:
        key = (case_id, arm)
        if key in risk_call_by_key:
            return risk_call_by_key[key]["item_id"]
        reply = results[key]["reply"]
        item_id = "rsmsv2risk_" + stable_hex(case_id, arm, "RISK")
        messages = risk_prompt_messages(item_id=item_id, dialogue=dialogue, reply=reply)
        call = {
            "logical_call_id": "rsmsv2riskcall_" + stable_hex(REVIEWER_ID, item_id),
            "kind": "risk",
            "case_id": case_id,
            "arm": arm,
            "owner_cluster": owner,
            "item_id": item_id,
            "messages": messages,
            "messages_sha256": sha256_text(canonical_json(messages)),
            "schema_sha256": sha256_text(canonical_json(RSMSRiskBlindReview.model_json_schema())),
            "seed": 20260813 + int(stable_hex(REVIEWER_ID, item_id, length=8), 16) % 100000,
            "temperature": 0.0,
            "max_output_tokens": 500,
        }
        risk_call_by_key[key] = call
        risk_calls.append(call)
        return item_id

    for case_id, case in sorted(cases.items()):
        owner = case["runtime_owner_key"]
        state = states[case["state_id"]]
        dialogue = _compact(state["current_user_text"])
        arms = set(case["arms_present"])

        # --- Risk: every reply this manifest needs, deduped per (case, arm) ---
        risk_m0r0 = get_risk_call(case_id, "M0+R0", owner, dialogue)
        risk_m0rs = get_risk_call(case_id, "M0+RS", owner, dialogue) if "M0+RS" in arms else None
        risk_msr0 = get_risk_call(case_id, "MS+R0", owner, dialogue) if "MS+R0" in arms else None

        # --- RS: Quality (M0+R0 vs M0+RS) + strategy realization ---
        rs_quality_id = None
        rs_function_id = None
        if "M0+RS" in arms:
            reply_m0r0 = results[(case_id, "M0+R0")]["reply"]
            reply_m0rs = results[(case_id, "M0+RS")]["reply"]
            pair_id = "rsv2pair_" + stable_hex(case_id, "RS_QUALITY")
            a_is_rs = int(stable_hex("AB", pair_id, length=2), 16) % 2 == 0
            reply_a = reply_m0rs if a_is_rs else reply_m0r0
            reply_b = reply_m0r0 if a_is_rs else reply_m0rs
            messages = quality_prompt_messages(pair_id=pair_id, dialogue=dialogue, reply_a=reply_a, reply_b=reply_b)
            quality_calls.append({
                "logical_call_id": "rsv2qualcall_" + stable_hex(REVIEWER_ID, pair_id),
                "kind": "rs_quality",
                "case_id": case_id,
                "owner_cluster": owner,
                "pair_id": pair_id,
                "a_arm": "M0+RS" if a_is_rs else "M0+R0",
                "b_arm": "M0+R0" if a_is_rs else "M0+RS",
                "messages": messages,
                "messages_sha256": sha256_text(canonical_json(messages)),
                "schema_sha256": sha256_text(canonical_json(RSMSQualityBlindReview.model_json_schema())),
                "seed": 20260813 + int(stable_hex(REVIEWER_ID, pair_id, length=8), 16) % 100000,
                "temperature": 0.0,
                "max_output_tokens": 500,
            })
            rs_quality_id = pair_id

            card = cards[case["rs_card_id"]]
            fn_id = "rsv2strategy_" + stable_hex(case_id, "RS_STRATEGY")
            fn_messages = function_prompt_messages(
                blind_item_id=fn_id,
                current_context=dialogue,
                authorized_resource_label=f"RS strategy card ({card.get('strategy_family')})",
                authorized_resource_text=str(card.get("retrieval_text", "")),
                reply=reply_m0rs,
            )
            function_calls.append({
                "logical_call_id": "rsv2strategycall_" + stable_hex(REVIEWER_ID, fn_id),
                "kind": "rs_strategy_realization",
                "case_id": case_id,
                "owner_cluster": owner,
                "arm_judged": "M0+RS",
                "blind_item_id": fn_id,
                "messages": fn_messages,
                "messages_sha256": sha256_text(canonical_json(fn_messages)),
                "schema_sha256": sha256_text(canonical_json(FunctionObservabilityV2BlindReview.model_json_schema())),
                "seed": 20260813 + int(stable_hex(REVIEWER_ID, fn_id, length=8), 16) % 100000,
                "temperature": 0.0,
                "max_output_tokens": 500,
            })
            rs_function_id = fn_id

        # --- MS: Quality (M0+R0 vs MS+R0) ---
        ms_quality_id = None
        if "MS+R0" in arms:
            reply_m0r0 = results[(case_id, "M0+R0")]["reply"]
            reply_msr0 = results[(case_id, "MS+R0")]["reply"]
            pair_id = "rsv2pair_" + stable_hex(case_id, "MS_QUALITY")
            a_is_ms = int(stable_hex("AB", pair_id, length=2), 16) % 2 == 0
            reply_a = reply_msr0 if a_is_ms else reply_m0r0
            reply_b = reply_m0r0 if a_is_ms else reply_msr0
            messages = quality_prompt_messages(pair_id=pair_id, dialogue=dialogue, reply_a=reply_a, reply_b=reply_b)
            quality_calls.append({
                "logical_call_id": "rsv2qualcall_" + stable_hex(REVIEWER_ID, pair_id),
                "kind": "ms_quality",
                "case_id": case_id,
                "owner_cluster": owner,
                "pair_id": pair_id,
                "a_arm": "MS+R0" if a_is_ms else "M0+R0",
                "b_arm": "M0+R0" if a_is_ms else "MS+R0",
                "messages": messages,
                "messages_sha256": sha256_text(canonical_json(messages)),
                "schema_sha256": sha256_text(canonical_json(RSMSQualityBlindReview.model_json_schema())),
                "seed": 20260813 + int(stable_hex(REVIEWER_ID, pair_id, length=8), 16) % 100000,
                "temperature": 0.0,
                "max_output_tokens": 500,
            })
            ms_quality_id = pair_id

        # --- MS Function independent re-verification + interaction crowd-out ---
        ms_function_id = None
        interaction_function_id = None
        if case["stratum"] in FUNCTION_STATES:
            ms_source = case["ms_exact_source"]
            reply_msr0 = results[(case_id, "MS+R0")]["reply"]
            fn_id = "rsv2msfunction_" + stable_hex(case_id, "MS_FUNCTION")
            fn_messages = function_prompt_messages(
                blind_item_id=fn_id,
                current_context=dialogue,
                authorized_resource_label="strictly past user-owned MS source",
                authorized_resource_text=ms_source,
                reply=reply_msr0,
            )
            function_calls.append({
                "logical_call_id": "rsv2msfunctioncall_" + stable_hex(REVIEWER_ID, fn_id),
                "kind": "ms_function_independent",
                "case_id": case_id,
                "owner_cluster": owner,
                "arm_judged": "MS+R0",
                "blind_item_id": fn_id,
                "messages": fn_messages,
                "messages_sha256": sha256_text(canonical_json(fn_messages)),
                "schema_sha256": sha256_text(canonical_json(FunctionObservabilityV2BlindReview.model_json_schema())),
                "seed": 20260813 + int(stable_hex(REVIEWER_ID, fn_id, length=8), 16) % 100000,
                "temperature": 0.0,
                "max_output_tokens": 500,
            })
            ms_function_id = fn_id

            if "MS+RS" in arms:
                reply_msrs = results[(case_id, "MS+RS")]["reply"]
                int_id = "rsv2interaction_" + stable_hex(case_id, "MS_RS_INTERACTION")
                int_messages = function_prompt_messages(
                    blind_item_id=int_id,
                    current_context=dialogue,
                    authorized_resource_label="strictly past user-owned MS source",
                    authorized_resource_text=ms_source,
                    reply=reply_msrs,
                )
                function_calls.append({
                    "logical_call_id": "rsv2interactioncall_" + stable_hex(REVIEWER_ID, int_id),
                    "kind": "ms_rs_interaction_crowdout",
                    "case_id": case_id,
                    "owner_cluster": owner,
                    "arm_judged": "MS+RS",
                    "blind_item_id": int_id,
                    "messages": int_messages,
                    "messages_sha256": sha256_text(canonical_json(int_messages)),
                    "schema_sha256": sha256_text(canonical_json(FunctionObservabilityV2BlindReview.model_json_schema())),
                    "seed": 20260813 + int(stable_hex(REVIEWER_ID, int_id, length=8), 16) % 100000,
                    "temperature": 0.0,
                    "max_output_tokens": 500,
                })
                interaction_function_id = int_id

        private_map.append({
            "case_id": case_id,
            "owner_cluster": owner,
            "stratum": case["stratum"],
            "risk_m0r0_item_id": risk_m0r0,
            "risk_m0rs_item_id": risk_m0rs,
            "risk_msr0_item_id": risk_msr0,
            "rs_quality_pair_id": rs_quality_id,
            "rs_strategy_function_id": rs_function_id,
            "ms_quality_pair_id": ms_quality_id,
            "ms_function_independent_id": ms_function_id,
            "ms_rs_interaction_function_id": interaction_function_id,
        })

    quality_calls.sort(key=lambda row: stable_hex("Q_ORDER", row["logical_call_id"]))
    risk_calls.sort(key=lambda row: stable_hex("R_ORDER", row["logical_call_id"]))
    function_calls.sort(key=lambda row: stable_hex("F_ORDER", row["logical_call_id"]))
    private_map.sort(key=lambda row: row["case_id"])

    all_calls = quality_calls + risk_calls + function_calls
    run_identity = sha256_text(
        canonical_json({
            "stage": STAGE,
            "call_plan": [row["logical_call_id"] for row in all_calls],
            "call_plan_messages_sha256": [row["messages_sha256"] for row in all_calls],
        })
    )

    release_manifest = read_json(RELEASE_MANIFEST)
    consumed_identities = {
        str(record.get("approval_identity") or record.get("run_identity") or "")
        for record in [
            *(release_manifest.get("stage_consumptions") or {}).values(),
            *(release_manifest.get("prior_stage_attempts_history") or []),
            *(release_manifest.get("stage_consumptions_history") or []),
        ]
        if isinstance(record, dict)
    }

    owner_clusters = sorted({row["owner_cluster"] for row in private_map})
    estimated_usd = round(
        len(quality_calls + risk_calls) * QUALITY_RISK_USD_PER_CALL
        + len(function_calls) * FUNCTION_USD_PER_CALL,
        4,
    )

    forbidden = ("generator_claimed", "used_evidence_ids", "requested_action_id")
    provider_text = canonical_json([row["messages"] for row in all_calls])
    checks = {
        "no_new_generation_all_replies_reused": True,
        "thirteen_states_present": len(private_map) == 13,
        "risk_calls_deduped_per_case_arm": len(risk_calls) == len({(c["case_id"], c["arm"]) for c in risk_calls}),
        "quality_position_randomized": (
            0 < sum(1 for row in quality_calls if row["kind"] == "rs_quality" and row["a_arm"] == "M0+RS") < len([r for r in quality_calls if r["kind"] == "rs_quality"])
        ),
        "function_calls_cover_seven_clear_use_and_ask_states_twice": sum(
            1 for row in function_calls if row["kind"] in ("ms_function_independent", "ms_rs_interaction_crowdout")
        ) == 14,
        "one_schema_per_kind": (
            len({row["schema_sha256"] for row in quality_calls}) == 1
            and len({row["schema_sha256"] for row in risk_calls}) == 1
            and len({row["schema_sha256"] for row in function_calls}) == 1
        ),
        "condition_and_arm_labels_absent_from_provider_text": not any(token in provider_text for token in forbidden),
        "owner_cluster_present_on_every_call": all("owner_cluster" in row for row in all_calls),
        "run_identity_not_previously_consumed_or_pending": run_identity not in consumed_identities,
    }
    if not all(checks.values()):
        raise RuntimeError(f"manifest self-check failed: {checks}")

    write_jsonl(OUT / "quality_calls_private.jsonl", quality_calls)
    write_jsonl(OUT / "risk_calls_private.jsonl", risk_calls)
    write_jsonl(OUT / "function_calls_private.jsonl", function_calls)
    write_jsonl(OUT / "private_map.jsonl", private_map)

    report = {
        "protocol": "pm-v1.5-paper1-rs-ms-panel-v2-blind-review-manifest-v1",
        "status": "PREFLIGHT_READY_HUMAN_APPROVAL_REQUIRED_BEFORE_ANY_JUDGE_CALL",
        "source": "outputs/pm_v1_5_paper1_rs_ms_panel_v2_live_20260813/generator_results_private.jsonl (50/50 real replies, no new generation)",
        "instrument": {
            "quality_and_risk": "v1_5_rs_ms_quality_risk_blind_review.py (unmodified, same as every prior track)",
            "function": "v1_5_function_observability_v2_blind_review.py (new this round: CLEAR/PLAUSIBLE/NONE/UNCERTAIN, blind to arm, shown the authorized source/card)",
        },
        "reviewer_id": REVIEWER_ID,
        "endpoint_key": ENDPOINT_KEY,
        "judge_model": "gpt-5.6-sol",
        "call_counts": {
            "rs_quality": sum(1 for r in quality_calls if r["kind"] == "rs_quality"),
            "ms_quality": sum(1 for r in quality_calls if r["kind"] == "ms_quality"),
            "risk_absolute": len(risk_calls),
            "rs_strategy_realization": sum(1 for r in function_calls if r["kind"] == "rs_strategy_realization"),
            "ms_function_independent": sum(1 for r in function_calls if r["kind"] == "ms_function_independent"),
            "ms_rs_interaction_crowdout": sum(1 for r in function_calls if r["kind"] == "ms_rs_interaction_crowdout"),
            "total": len(all_calls),
        },
        "owner_clusters": {
            "count": len(owner_clusters),
            "members": owner_clusters,
            "note": "evo::p1 contributes 2 of the 13 panel states; every table computed from this manifest's results must report both state-level and owner-cluster-level counts, matching the correction in paper1_panel_v2_owner_cluster_correction_and_roadmap_v1.json.",
        },
        "estimated_usd": estimated_usd,
        "estimated_usd_basis": f"{QUALITY_RISK_USD_PER_CALL}/call for quality+risk (historical blended rate, 57 calls / $0.5756 actual); {FUNCTION_USD_PER_CALL}/call for Function-style calls (estimated higher, more context per call)",
        "run_identity": run_identity,
        "checks": checks,
        "next_action": "Present this exact run identity, call count, and cost cap for explicit human approval before any judge call. No live execution is authorized by this script.",
        "api_calls": 0,
    }
    write_json(OUT / "report.json", report)
    print(json.dumps(report, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
